#!/bin/bash

#Script: Ops 201 Class 06 Ops Challenge Solution
#Author: Cameron Griffin
#Date of latest revision: 11-10-2022
#Purpose: Creata an array and delete files in array


# Create a script that detects if a file or directory exists, then creates it if it does not exist.
# Your script must use at least one array, one loop, and one conditional.

